// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/budget.dart';
import 'src/models/category.dart';
import 'src/models/money_source.dart';
import 'src/models/savings_goal.dart';
import 'src/models/transaction.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 493840073215639006),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(9, 5355821334302738222),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2658151289738368256),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8798518330385807226),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9184763389241388492),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1098556984725636502),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8780093849475352077),
        name: 'dbIconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2642247201244125195),
        name: 'colorHex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6351988202522147402),
        name: 'dbType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4790256536881766510),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8568673951023825635),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5355821334302738222),
        name: 'typeCode',
        type: 2,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7804320392523648537),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(12, 5819948035215699391),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3534865314686460723),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4020198000258808557),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 3815019248116518036),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6585591289071833955),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7694956556133934214),
        name: 'dbType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 794889022503360791),
        name: 'categoryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 8670739179309655836),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3647100077234859793),
        name: 'date',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(6, 8079795347682836557),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1291458765582326682),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6331285137163730624),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(7, 9158010454404252001),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1304849199539883312),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7162688059454464275),
        name: 'typeCode',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3743505230492404707),
        name: 'sourceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 5507329943214301050),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5819948035215699391),
        name: 'savingsGoalId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 1091651197108033581),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6814073455354518124),
    name: 'MoneySource',
    lastPropertyId: const obx_int.IdUid(6, 593030572791077501),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7202591951073276106),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4685231358784153688),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 1626306486108024305),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 712825919219107123),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4246415566177783395),
        name: 'dbIconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5110593064283057779),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 593030572791077501),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4449110663233528591),
    name: 'SavingsGoal',
    lastPropertyId: const obx_int.IdUid(13, 7252998695314141752),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4640397952089517882),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3396422360137261182),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 7357680742283767692),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1128947346705756346),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5225968569058340931),
        name: 'targetAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3273161100223818518),
        name: 'savedAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6678201446676429553),
        name: 'deadline',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7034784935062051904),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7898982240400800410),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2282060080335797069),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(11, 8219870922745221666),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8519554436366512149),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5368346050396594622),
        name: 'startDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(12, 3254630399225974344),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8506350822989154819),
        name: 'dbIconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7252998695314141752),
        name: 'colorHex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5027326062470403617),
    name: 'Budget',
    lastPropertyId: const obx_int.IdUid(9, 7680539986417524578),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5492822279000084004),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 195958745756149980),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(14, 1707014768316864259),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8193943846200550975),
        name: 'categoryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(15, 2870329007639757159),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 856484352848977374),
        name: 'limitAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4424175570079819775),
        name: 'periodStart',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(16, 8873063483196581557),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6887893767136089472),
        name: 'warningPercent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 955996273534305911),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9071170801313566729),
        name: 'updatedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(17, 1741580117996319481),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7680539986417524578),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 5027326062470403617),
    lastIndexId: const obx_int.IdUid(17, 1741580117996319481),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2958872209723789033, 7083601830508858313],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4003052579714602889,
      6710834331620792108,
      254034798580907153,
      6618849966409149179,
      8142406804263285886,
      7977654457734510040,
      9168998820421062569,
      1545797507743200257,
      4700651710094626068,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[0],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {},
      getId: (Category object) => object.obxId,
      setId: (Category object, int id) {
        object.obxId = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final dbTypeOffset = object.dbType == null
            ? null
            : fbb.writeString(object.dbType!);
        fbb.startTable(10);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.dbIconCodePoint);
        fbb.addInt64(4, object.colorHex);
        fbb.addOffset(5, dbTypeOffset);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isDeleted);
        fbb.addInt8(8, object.typeCode);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dbIconCodePointParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final colorHexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final typeCodeParam = const fb.Int8Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final dbTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = Category(
          obxId: obxIdParam,
          id: idParam,
          name: nameParam,
          dbIconCodePoint: dbIconCodePointParam,
          colorHex: colorHexParam,
          typeCode: typeCodeParam,
          dbType: dbTypeParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[1],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.obxId,
      setId: (Transaction object, int id) {
        object.obxId = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final dbTypeOffset = object.dbType == null
            ? null
            : fbb.writeString(object.dbType!);
        final categoryIdOffset = fbb.writeString(object.categoryId);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final sourceIdOffset = fbb.writeString(object.sourceId);
        final savingsGoalIdOffset = object.savingsGoalId == null
            ? null
            : fbb.writeString(object.savingsGoalId!);
        fbb.startTable(13);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, dbTypeOffset);
        fbb.addOffset(4, categoryIdOffset);
        fbb.addInt64(5, object.date.millisecondsSinceEpoch);
        fbb.addOffset(6, noteOffset);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(8, object.isDeleted);
        fbb.addInt8(9, object.typeCode);
        fbb.addOffset(10, sourceIdOffset);
        fbb.addOffset(11, savingsGoalIdOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final typeCodeParam = const fb.Int8Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final dbTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final sourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final savingsGoalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = Transaction(
          obxId: obxIdParam,
          id: idParam,
          amount: amountParam,
          typeCode: typeCodeParam,
          dbType: dbTypeParam,
          categoryId: categoryIdParam,
          sourceId: sourceIdParam,
          savingsGoalId: savingsGoalIdParam,
          date: dateParam,
          note: noteParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    MoneySource: obx_int.EntityDefinition<MoneySource>(
      model: _entities[2],
      toOneRelations: (MoneySource object) => [],
      toManyRelations: (MoneySource object) => {},
      getId: (MoneySource object) => object.obxId,
      setId: (MoneySource object, int id) {
        object.obxId = id;
      },
      objectToFB: (MoneySource object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.dbIconCodePoint);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dbIconCodePointParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = MoneySource(
          obxId: obxIdParam,
          id: idParam,
          name: nameParam,
          dbIconCodePoint: dbIconCodePointParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    SavingsGoal: obx_int.EntityDefinition<SavingsGoal>(
      model: _entities[3],
      toOneRelations: (SavingsGoal object) => [],
      toManyRelations: (SavingsGoal object) => {},
      getId: (SavingsGoal object) => object.obxId,
      setId: (SavingsGoal object, int id) {
        object.obxId = id;
      },
      objectToFB: (SavingsGoal object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(14);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.targetAmount);
        fbb.addFloat64(4, object.savedAmount);
        fbb.addInt64(5, object.deadline?.millisecondsSinceEpoch);
        fbb.addOffset(6, noteOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(9, object.isDeleted);
        fbb.addInt64(10, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(11, object.dbIconCodePoint);
        fbb.addInt64(12, object.colorHex);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deadlineValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final targetAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final savedAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dbIconCodePointParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final colorHexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final deadlineParam = deadlineValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deadlineValue);
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = SavingsGoal(
          obxId: obxIdParam,
          id: idParam,
          title: titleParam,
          targetAmount: targetAmountParam,
          savedAmount: savedAmountParam,
          dbIconCodePoint: dbIconCodePointParam,
          colorHex: colorHexParam,
          startDate: startDateParam,
          deadline: deadlineParam,
          note: noteParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    Budget: obx_int.EntityDefinition<Budget>(
      model: _entities[4],
      toOneRelations: (Budget object) => [],
      toManyRelations: (Budget object) => {},
      getId: (Budget object) => object.obxId,
      setId: (Budget object, int id) {
        object.obxId = id;
      },
      objectToFB: (Budget object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final categoryIdOffset = fbb.writeString(object.categoryId);
        fbb.startTable(10);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, categoryIdOffset);
        fbb.addFloat64(3, object.limitAmount);
        fbb.addInt64(4, object.periodStart.millisecondsSinceEpoch);
        fbb.addFloat64(5, object.warningPercent);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final limitAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final periodStartParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final warningPercentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = Budget(
          obxId: obxIdParam,
          id: idParam,
          categoryId: categoryIdParam,
          limitAmount: limitAmountParam,
          periodStart: periodStartParam,
          warningPercent: warningPercentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.obxId].
  static final obxId = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[0],
  );

  /// See [Category.id].
  static final id = obx.QueryStringProperty<Category>(
    _entities[0].properties[1],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[0].properties[2],
  );

  /// See [Category.dbIconCodePoint].
  static final dbIconCodePoint = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[3],
  );

  /// See [Category.colorHex].
  static final colorHex = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[4],
  );

  /// See [Category.dbType].
  static final dbType = obx.QueryStringProperty<Category>(
    _entities[0].properties[5],
  );

  /// See [Category.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Category>(
    _entities[0].properties[6],
  );

  /// See [Category.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Category>(
    _entities[0].properties[7],
  );

  /// See [Category.typeCode].
  static final typeCode = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[8],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.obxId].
  static final obxId = obx.QueryIntegerProperty<Transaction>(
    _entities[1].properties[0],
  );

  /// See [Transaction.id].
  static final id = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[1],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[1].properties[2],
  );

  /// See [Transaction.dbType].
  static final dbType = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[3],
  );

  /// See [Transaction.categoryId].
  static final categoryId = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[4],
  );

  /// See [Transaction.date].
  static final date = obx.QueryDateProperty<Transaction>(
    _entities[1].properties[5],
  );

  /// See [Transaction.note].
  static final note = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[6],
  );

  /// See [Transaction.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Transaction>(
    _entities[1].properties[7],
  );

  /// See [Transaction.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Transaction>(
    _entities[1].properties[8],
  );

  /// See [Transaction.typeCode].
  static final typeCode = obx.QueryIntegerProperty<Transaction>(
    _entities[1].properties[9],
  );

  /// See [Transaction.sourceId].
  static final sourceId = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[10],
  );

  /// See [Transaction.savingsGoalId].
  static final savingsGoalId = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[11],
  );
}

/// [MoneySource] entity fields to define ObjectBox queries.
class MoneySource_ {
  /// See [MoneySource.obxId].
  static final obxId = obx.QueryIntegerProperty<MoneySource>(
    _entities[2].properties[0],
  );

  /// See [MoneySource.id].
  static final id = obx.QueryStringProperty<MoneySource>(
    _entities[2].properties[1],
  );

  /// See [MoneySource.name].
  static final name = obx.QueryStringProperty<MoneySource>(
    _entities[2].properties[2],
  );

  /// See [MoneySource.dbIconCodePoint].
  static final dbIconCodePoint = obx.QueryIntegerProperty<MoneySource>(
    _entities[2].properties[3],
  );

  /// See [MoneySource.updatedAt].
  static final updatedAt = obx.QueryDateProperty<MoneySource>(
    _entities[2].properties[4],
  );

  /// See [MoneySource.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<MoneySource>(
    _entities[2].properties[5],
  );
}

/// [SavingsGoal] entity fields to define ObjectBox queries.
class SavingsGoal_ {
  /// See [SavingsGoal.obxId].
  static final obxId = obx.QueryIntegerProperty<SavingsGoal>(
    _entities[3].properties[0],
  );

  /// See [SavingsGoal.id].
  static final id = obx.QueryStringProperty<SavingsGoal>(
    _entities[3].properties[1],
  );

  /// See [SavingsGoal.title].
  static final title = obx.QueryStringProperty<SavingsGoal>(
    _entities[3].properties[2],
  );

  /// See [SavingsGoal.targetAmount].
  static final targetAmount = obx.QueryDoubleProperty<SavingsGoal>(
    _entities[3].properties[3],
  );

  /// See [SavingsGoal.savedAmount].
  static final savedAmount = obx.QueryDoubleProperty<SavingsGoal>(
    _entities[3].properties[4],
  );

  /// See [SavingsGoal.deadline].
  static final deadline = obx.QueryDateProperty<SavingsGoal>(
    _entities[3].properties[5],
  );

  /// See [SavingsGoal.note].
  static final note = obx.QueryStringProperty<SavingsGoal>(
    _entities[3].properties[6],
  );

  /// See [SavingsGoal.createdAt].
  static final createdAt = obx.QueryDateProperty<SavingsGoal>(
    _entities[3].properties[7],
  );

  /// See [SavingsGoal.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SavingsGoal>(
    _entities[3].properties[8],
  );

  /// See [SavingsGoal.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<SavingsGoal>(
    _entities[3].properties[9],
  );

  /// See [SavingsGoal.startDate].
  static final startDate = obx.QueryDateProperty<SavingsGoal>(
    _entities[3].properties[10],
  );

  /// See [SavingsGoal.dbIconCodePoint].
  static final dbIconCodePoint = obx.QueryIntegerProperty<SavingsGoal>(
    _entities[3].properties[11],
  );

  /// See [SavingsGoal.colorHex].
  static final colorHex = obx.QueryIntegerProperty<SavingsGoal>(
    _entities[3].properties[12],
  );
}

/// [Budget] entity fields to define ObjectBox queries.
class Budget_ {
  /// See [Budget.obxId].
  static final obxId = obx.QueryIntegerProperty<Budget>(
    _entities[4].properties[0],
  );

  /// See [Budget.id].
  static final id = obx.QueryStringProperty<Budget>(_entities[4].properties[1]);

  /// See [Budget.categoryId].
  static final categoryId = obx.QueryStringProperty<Budget>(
    _entities[4].properties[2],
  );

  /// See [Budget.limitAmount].
  static final limitAmount = obx.QueryDoubleProperty<Budget>(
    _entities[4].properties[3],
  );

  /// See [Budget.periodStart].
  static final periodStart = obx.QueryDateProperty<Budget>(
    _entities[4].properties[4],
  );

  /// See [Budget.warningPercent].
  static final warningPercent = obx.QueryDoubleProperty<Budget>(
    _entities[4].properties[5],
  );

  /// See [Budget.createdAt].
  static final createdAt = obx.QueryDateProperty<Budget>(
    _entities[4].properties[6],
  );

  /// See [Budget.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Budget>(
    _entities[4].properties[7],
  );

  /// See [Budget.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Budget>(
    _entities[4].properties[8],
  );
}
