// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/app_setting.dart';
import 'src/models/auth_user.dart';
import 'src/models/category.dart';
import 'src/models/transaction.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 493840073215639006),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(8, 8568673951023825635),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2658151289738368256),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8798518330385807226),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9184763389241388492),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1098556984725636502),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8780093849475352077),
        name: 'dbIconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2642247201244125195),
        name: 'colorHex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6351988202522147402),
        name: 'dbType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4790256536881766510),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8568673951023825635),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7804320392523648537),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(9, 1304849199539883312),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3534865314686460723),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4020198000258808557),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 3815019248116518036),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6585591289071833955),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7694956556133934214),
        name: 'dbType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 794889022503360791),
        name: 'categoryId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3647100077234859793),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1291458765582326682),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6331285137163730624),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1304849199539883312),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2958872209723789033),
    name: 'AppSetting',
    lastPropertyId: const obx_int.IdUid(3, 254034798580907153),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4003052579714602889),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6710834331620792108),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7307916399414270491),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 254034798580907153),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7083601830508858313),
    name: 'AuthUser',
    lastPropertyId: const obx_int.IdUid(6, 4700651710094626068),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6618849966409149179),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8142406804263285886),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 610653384527144065),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7977654457734510040),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9168998820421062569),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1545797507743200257),
        name: 'lastLoginAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4700651710094626068),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7083601830508858313),
    lastIndexId: const obx_int.IdUid(4, 610653384527144065),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[0],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {},
      getId: (Category object) => object.obxId,
      setId: (Category object, int id) {
        object.obxId = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final dbTypeOffset = fbb.writeString(object.dbType);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.dbIconCodePoint);
        fbb.addInt64(4, object.colorHex);
        fbb.addOffset(5, dbTypeOffset);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dbIconCodePointParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final colorHexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dbTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = Category(
          obxId: obxIdParam,
          id: idParam,
          name: nameParam,
          dbIconCodePoint: dbIconCodePointParam,
          colorHex: colorHexParam,
          dbType: dbTypeParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[1],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.obxId,
      setId: (Transaction object, int id) {
        object.obxId = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final dbTypeOffset = fbb.writeString(object.dbType);
        final categoryIdOffset = fbb.writeString(object.categoryId);
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(10);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, dbTypeOffset);
        fbb.addOffset(4, categoryIdOffset);
        fbb.addInt64(5, object.date.millisecondsSinceEpoch);
        fbb.addOffset(6, noteOffset);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dbTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = Transaction(
          obxId: obxIdParam,
          id: idParam,
          amount: amountParam,
          dbType: dbTypeParam,
          categoryId: categoryIdParam,
          date: dateParam,
          note: noteParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    AppSetting: obx_int.EntityDefinition<AppSetting>(
      model: _entities[2],
      toOneRelations: (AppSetting object) => [],
      toManyRelations: (AppSetting object) => {},
      getId: (AppSetting object) => object.id,
      setId: (AppSetting object, int id) {
        object.id = id;
      },
      objectToFB: (AppSetting object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = AppSetting(
          id: idParam,
          key: keyParam,
          value: valueParam,
        );

        return object;
      },
    ),
    AuthUser: obx_int.EntityDefinition<AuthUser>(
      model: _entities[3],
      toOneRelations: (AuthUser object) => [],
      toManyRelations: (AuthUser object) => {},
      getId: (AuthUser object) => object.obxId,
      setId: (AuthUser object, int id) {
        object.obxId = id;
      },
      objectToFB: (AuthUser object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final emailOffset = fbb.writeString(object.email);
        final nameOffset = fbb.writeString(object.name);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        fbb.startTable(7);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addInt64(4, object.lastLoginAt.millisecondsSinceEpoch);
        fbb.addOffset(5, photoUrlOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastLoginAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = AuthUser(
          obxId: obxIdParam,
          id: idParam,
          email: emailParam,
          name: nameParam,
          lastLoginAt: lastLoginAtParam,
          photoUrl: photoUrlParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.obxId].
  static final obxId = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[0],
  );

  /// See [Category.id].
  static final id = obx.QueryStringProperty<Category>(
    _entities[0].properties[1],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[0].properties[2],
  );

  /// See [Category.dbIconCodePoint].
  static final dbIconCodePoint = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[3],
  );

  /// See [Category.colorHex].
  static final colorHex = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[4],
  );

  /// See [Category.dbType].
  static final dbType = obx.QueryStringProperty<Category>(
    _entities[0].properties[5],
  );

  /// See [Category.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Category>(
    _entities[0].properties[6],
  );

  /// See [Category.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Category>(
    _entities[0].properties[7],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.obxId].
  static final obxId = obx.QueryIntegerProperty<Transaction>(
    _entities[1].properties[0],
  );

  /// See [Transaction.id].
  static final id = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[1],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[1].properties[2],
  );

  /// See [Transaction.dbType].
  static final dbType = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[3],
  );

  /// See [Transaction.categoryId].
  static final categoryId = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[4],
  );

  /// See [Transaction.date].
  static final date = obx.QueryDateProperty<Transaction>(
    _entities[1].properties[5],
  );

  /// See [Transaction.note].
  static final note = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[6],
  );

  /// See [Transaction.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Transaction>(
    _entities[1].properties[7],
  );

  /// See [Transaction.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Transaction>(
    _entities[1].properties[8],
  );
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.id].
  static final id = obx.QueryIntegerProperty<AppSetting>(
    _entities[2].properties[0],
  );

  /// See [AppSetting.key].
  static final key = obx.QueryStringProperty<AppSetting>(
    _entities[2].properties[1],
  );

  /// See [AppSetting.value].
  static final value = obx.QueryStringProperty<AppSetting>(
    _entities[2].properties[2],
  );
}

/// [AuthUser] entity fields to define ObjectBox queries.
class AuthUser_ {
  /// See [AuthUser.obxId].
  static final obxId = obx.QueryIntegerProperty<AuthUser>(
    _entities[3].properties[0],
  );

  /// See [AuthUser.id].
  static final id = obx.QueryStringProperty<AuthUser>(
    _entities[3].properties[1],
  );

  /// See [AuthUser.email].
  static final email = obx.QueryStringProperty<AuthUser>(
    _entities[3].properties[2],
  );

  /// See [AuthUser.name].
  static final name = obx.QueryStringProperty<AuthUser>(
    _entities[3].properties[3],
  );

  /// See [AuthUser.lastLoginAt].
  static final lastLoginAt = obx.QueryDateProperty<AuthUser>(
    _entities[3].properties[4],
  );

  /// See [AuthUser.photoUrl].
  static final photoUrl = obx.QueryStringProperty<AuthUser>(
    _entities[3].properties[5],
  );
}
